Rapper.create!(name:"Lil Nas X", age: 20)
Rapper.create!(name:"Kendrick Lamar", age:32)
Rapper.create!(name:"Lil Dicky", age: 31)
Rapper.create!(name:"Tyler, The Creator", age:28)
Rapper.create!(name:"Cardi B", age:26)
Rapper.create!(name:"Nicki Minaj", age:36)
Rapper.create!(name:"Lady Leshurr", age:30)
